<a href="https://colab.research.google.com/github/joanby/trading-algoritmico-a-z-con-python/blob/main/ES_TA_Cap%C3%ADtulo_02_Python_para_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p><img alt="Colaboratory logo" height="45px" src="https://www.quantreo.com/wp-content/uploads/2021/10/Original-on-Transparent.png" align="left" hspace="10px" vspace="0px">
<img alt="Colaboratory logo" height="45px" src="https://static-881c.kxcdn.com/wp-content/uploads/2016/03/frogamesLogoFull4.png" align="left" hspace="10px" vspace="0px"></p>


# PRERREQUISITOS  - **Python para Data Science**

Este capítulo te dará los fundamentos de python para ciencia de  datos que necesitas para seguir el resto del curso. Estos son sólo recordatorios de lo que será útil. Por eso te aconsejo que sigas una formación rápida y gratuita de Python para tus proyectos, porque si eres totalmente ajeno a él, puede ser difícil hacer tu proyecto. Nosotros te recomendamos el curso de más de 50 horas de programación, [Python de la A a la Z que puedes obtener desde nuestra web de frogames](https://cursos.frogamesformacion.com/courses/python-az/).


* Numpy:
> * Creación de tablas con Numpy
> * Aleatoriedad con Numpy
> * Indexación y Slicing

* Pandas:
> * Series y dataframe 
> * Funciones útiles de pandas
> * Indexación y Slicing

* Matplotlib
> * Gráficos
> * Nubes de puntos
> * Funciones útiles


💰 Únete a la comunidad de [Discord](https://discord.gg/z3dx5XpkX4)

📚 Puedes leer nuestro libro en [Amazon](https://www.amazon.es/Python-para-finanzas-trading-algor%C3%ADtmico-ebook/dp/B0BT4ZS9Q3/)

🖥️ El canal de [YouTube de Quantreo's](https://www.youtube.com/channel/UCp7jckfiEglNf_Gj62VR0pw) (en inglés) y el de [Frogames](https://www.youtube.com/channel/UCMUxXNYrVCv6-bQakhomvBg) en español








### Numpy

##### Creación de tablas con Numpy

In [13]:
# Import de numpy

import numpy as np

# 1D array
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
# Función Linspace
np.linspace(0, 50, 51)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [5]:
# Función Arange 
np.arange(0,51)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [9]:
# 2D array
arr_bis = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
arr_bis

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# Matriz de Ceros
O = np.zeros([3,5])
O

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
# Matriz Identidad
I = np.identity(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
# Matriz de Unos
One = np.ones([3,5])
One

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
# Sumar dos matrices
O + One

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
# Restar dos matrices
One-O

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
# Producto por escalar
One * 10

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

##### Random

In [10]:
# Matriz aleatoria 1d con valores entre 0 y 1 (Ideal para simular un peso aleatorio de una cartera por ejemplo)
ran = np.random.rand(6)
ran

array([0.32662702, 0.76859722, 0.29800789, 0.44973423, 0.0467521 ,
       0.40029   ])

In [11]:
# BONUS: Cómo encontrar la forma de un array y transformar un array 1d en un array 2d
print(f"Shape es {np.shape(ran)}")

# Reshape
ran = ran.reshape(-1,1)

# Nueva forma
print(f"Shape es {np.shape(ran)}")

Shape es (6,)
Shape es (6, 1)


In [12]:
ran

array([[0.32662702],
       [0.76859722],
       [0.29800789],
       [0.44973423],
       [0.0467521 ],
       [0.40029   ]])

In [21]:
# Valores aleatorios enteros
arr_int = np.random.randint(100, size=(5,5))
arr_int

array([[31, 68, 60, 15,  4],
       [19, 28, 88, 64, 84],
       [89, 88, 28, 55, 46],
       [88, 67, 56, 56, 99],
       [67, 65, 10, 65, 78]])

In [22]:
# Distribución normal 1 Dim
np.random.normal(loc=0, scale=0.1, size=(6,))

array([ 0.0317041 , -0.00369426,  0.07927536,  0.08888987, -0.02801485,
        0.0061748 ])

In [28]:
# Distribución normal 2 Dim
np.random.normal(loc=0, scale=0.1, size=(6,6))

array([[-0.18217544,  0.11776452,  0.08301567, -0.00486639, -0.03066252,
        -0.19389907],
       [ 0.33269801, -0.14701157, -0.00718461,  0.02619011, -0.03061681,
         0.07615358],
       [ 0.04384155,  0.07425683, -0.06842404, -0.1067052 , -0.00276035,
        -0.06787927],
       [-0.04390115, -0.04891286, -0.01618534,  0.14619283,  0.02678329,
         0.19601582],
       [ 0.08948065, -0.02855578,  0.07938803, -0.07630312,  0.1058048 ,
        -0.08884365],
       [ 0.03616659, -0.06043576, -0.0274361 ,  0.01434024,  0.11709511,
         0.11765874]])

In [35]:
# Establecer la semilla de la aleatoriedad
print(np.random.rand(3))
print(np.random.rand(3))

np.random.seed(seed=56)
print(np.random.rand(3))

np.random.seed(seed=56)
print(np.random.rand(3))

np.random.seed(seed=56)
print(np.random.rand(3))

[0.73784304 0.25688482 0.05579651]
[0.37668479 0.44209279 0.41497444]
[0.98419185 0.33341227 0.67370162]
[0.98419185 0.33341227 0.67370162]
[0.98419185 0.33341227 0.67370162]


##### Indices, Slicing y Transformaciones

In [14]:
# Elegir un valor en la matriz
arr_bis = np.array([[1,2,3],
                    [7,1,6],
                    [9,6,3]])
arr_bis[0,0]

1

In [12]:
# Elija la submatriz en la matriz
#Se escoge las 3 primeras filas y las dos primeras columnas
arr_bis[0:3,0:2]

array([[1, 2],
       [7, 1],
       [9, 6]])

In [15]:
# Elija una columna o una fila

print(arr_bis[0,:])
print(arr_bis[:,1])

[1 2 3]
[2 1 6]


In [23]:
# Maximo
# De la matriz
print(arr_bis.max())

# Max por filas 
# axis=1 -> segunda dimension
print(arr_bis.max(axis=1))

# Max por columnas
# axis=0 -> primera dimension
print(arr_bis.max(axis=0))

9
[3 7 9]
[9 6 6]


In [25]:
# Minino
# De la matriz
print(arr_bis.min())

# Min por filas 
# axis=1 -> segunda dimension
print(arr_bis.min(axis=1))

# Min por columnas
# axis=0 -> primera dimension

print(arr_bis.min(axis=0))

1
[1 1 3]
[1 1 3]


In [27]:
# Media - Promedio
# De la matriz
print(arr_bis.mean())

# Media por filas
# axis=1 -> segunda dimension
print(arr_bis.mean(axis=1))

# Por Columna
# axis=0 -> primera dimension
print(arr_bis.mean(axis=0))

4.222222222222222
[2.         4.66666667 6.        ]
[5.66666667 3.         4.        ]


In [35]:
# Desviacion Tipica std -> Standard desvi
# De la matriz 
print(arr_bis.std())

# Por filas
print("Desviacion por filas:",arr_bis.std(axis=1))

# Por Columna
print(arr_bis.std(axis=0))

# Otras formas
print("Numpy version directa ")
np.std(arr_bis,axis=1)
np.std(arr_bis,axis=0)

2.698879511442471
Desviacion por filas: [0.81649658 2.62466929 2.44948974]
[3.39934634 2.1602469  1.41421356]
Numpy version directa 


array([3.39934634, 2.1602469 , 1.41421356])

In [38]:
# Logaritmo
np.log(arr_bis)

array([[0.        , 0.69314718, 1.09861229],
       [1.94591015, 0.        , 1.79175947],
       [2.19722458, 1.79175947, 1.09861229]])

In [42]:
# Exponencial
np.exp(arr_bis)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [1.09663316e+03, 2.71828183e+00, 4.03428793e+02],
       [8.10308393e+03, 4.03428793e+02, 2.00855369e+01]])

In [43]:
# Raiz Cuadrada
np.sqrt(arr_bis)

array([[1.        , 1.41421356, 1.73205081],
       [2.64575131, 1.        , 2.44948974],
       [3.        , 2.44948974, 1.73205081]])

In [88]:
# Concatenar
# Parametro: tupla de arrays y el eje de la concatenacion
# Concatenar unidimensional
arr1 = arr_bis[:,1]
arr2 = arr_bis[:,2]

print(f"ARR1 {arr1}")
print(f"ARR2 {arr2}")

print(np.concatenate((arr1,arr2),axis=0))

ARR1 [2 1 6]
ARR2 [3 6 3]
[2 1 6 3 6 3]


In [97]:
# Concatenar 2 dimesiones - apendizar
arr1 = arr1.reshape(-1,1)
arr2 = arr2.reshape(-1,1)

print(f"ARR1 {arr1}")
print(f"ARR2 {arr2}")

print(f"Concatenacion {np.concatenate((arr1,arr2),axis=0)}")


ARR1 [[2]
 [1]
 [6]]
ARR2 [[3]
 [6]
 [3]]
Concatenacion [[2]
 [1]
 [6]
 [3]
 [6]
 [3]]


### Pandas

In [98]:
import pandas as pd
import numpy as np

##### Series - Unidimensional - se puede acceder utitlizando clave valor

In [109]:
labels = ["label 1","label 2","label 3"]
list_values = [1,2,3]
arr_values = np.array(list_values)

labels

['label 1', 'label 2', 'label 3']

In [117]:
# Crear una serie usando una lista - despues de crear se puede acceder utilizando par clave valor
pd.Series(list_values,index=labels)

label 1    1
label 2    2
label 3    3
dtype: int64

In [118]:
# Crear una serie usando un array - despues de crear se puede acceder utilizando par clave valor
pd.Series(arr_values,index=labels)

label 1    1
label 2    2
label 3    3
dtype: int64

##### Dataframes - Bidimensional - se puede acceder utitlizando clave valor

In [119]:
list_columns = ["Col_1", "Col_2", "Col_3"]
list_index = ["row_1", "row_2", "row_3"]

arr_bis = np.array([[1,2,3],
                    [7,1,6],
                    [9,6,9]]) 

In [122]:
# Crear un dataframe desde un array
pd.DataFrame(arr_bis)

0  1  2
0  1  2  3
1  7  1  6
2  9  6  9

In [123]:
# Converir en array desde un dataframes
pd.DataFrame(arr_bis).values

array([[1, 2, 3],
       [7, 1, 6],
       [9, 6, 9]])

In [124]:
# Especificar filas/columnas
pd.DataFrame(arr_bis,index=list_index,columns=list_columns)

Col_1  Col_2  Col_3
row_1      1      2      3
row_2      7      1      6
row_3      9      6      9

##### Cleaning and Selection

In [129]:
# Import un CSV
assets = pd.read_csv("./assets.csv", parse_dates=True, index_col="time")
assets

Open MSFT  High MSFT  Low MSFT  Close MSFT  Volume MSFT  \
time                                                                  
2020-03-18      138.0   146.0000    135.02      140.40   80794307.0   
2020-03-17      140.0   147.4998    135.00      146.57   81059817.0   
2020-03-16      140.0   149.3500    135.00      135.42   87905868.0   
2020-03-13      147.5   161.9100    140.73      158.83   92727446.0   
2020-03-12      145.3   153.4700    138.58      139.06   93226366.0   
...               ...        ...       ...         ...          ...   
2000-07-04        NaN        NaN       NaN         NaN          NaN   
2000-05-29        NaN        NaN       NaN         NaN          NaN   
2000-04-21        NaN        NaN       NaN         NaN          NaN   
2000-02-21        NaN        NaN       NaN         NaN          NaN   
2000-01-17        NaN        NaN       NaN         NaN          NaN   

            Open GOOG  High GOOG  Low GOOG  Close GOOG  Volume GOOG  ...  \
time                                                                 ...   
2020-03-18    1056.51    1106.50   1037.28     1096.80    4220935.0  ...   
2020-03-17    1093.11    1130.86   1056.01     1119.80    3861489.0  ...   
2020-03-16    1096.00    1152.27   1074.44     1084.33    4252365.0  ...   
2020-03-13    1179.00    1219.76   1117.14     1219.73    3700125.0  ...   
2020-03-12    1126.00    1193.87   1113.30     1114.91    4226748.0  ...   
...               ...        ...       ...         ...          ...  ...   
2000-07-04        NaN        NaN       NaN         NaN          NaN  ...   
2000-05-29        NaN        NaN       NaN         NaN          NaN  ...   
2000-04-21        NaN        NaN       NaN         NaN          NaN  ...   
2000-02-21        NaN        NaN       NaN         NaN          NaN  ...   
2000-01-17        NaN        NaN       NaN         NaN          NaN  ...   

            Open EUROSTOCK50  High EUROSTOCK50  Low EUROSTOCK50  \
time                                                              
2020-03-18         2507.3301         2507.3301        2365.7000   
2020-03-17         2475.1799         2555.4099        2376.2300   
2020-03-16         2557.7100         2557.7100        2302.8401   
2020-03-13         2584.3601         2793.2700        2537.2700   
2020-03-12         2883.2500         2883.2500        2535.8899   
...                      ...               ...              ...   
2000-07-04         5185.8701         5185.8701        5185.8701   
2000-05-29         5084.6899         5084.6899        5084.6899   
2000-04-21         5180.1184         5207.4892        5132.2034   
2000-02-21         5033.3301         5033.3301        5033.3301   
2000-01-17         4884.5000         4884.5000        4884.5000   

            Close EUROSTOCK50  Volume EUROSTOCK50  Open INTEL  High INTEL  \
time                                                                        
2020-03-18          2385.8201          98214900.0       30.24     32.4550   
2020-03-17          2530.5000         106905300.0       29.06     33.8000   
2020-03-16          2450.3701         137137000.0       30.11     32.8450   
2020-03-13          2586.0200         136547100.0       33.87     35.0077   
2020-03-12          2545.2300         167329900.0       35.29     36.0432   
...                       ...                 ...         ...         ...   
2000-07-04          5185.8701                 0.0         NaN         NaN   
2000-05-29          5084.6899                 0.0         NaN         NaN   
2000-04-21          5170.3844            722995.0         NaN         NaN   
2000-02-21          5033.3301                 0.0         NaN         NaN   
2000-01-17          4884.5000                 0.0         NaN         NaN   

            Low INTEL  Close INTEL  Volume INTEL  
time                                              
2020-03-18      28.01        29.20      192337.0  
2020-03-17      28.79        32.40      273967.0  
2020-03-16      28.62

In [131]:
# Ordenar
assets = assets.sort_index(ascending=True)
assets

Open MSFT  High MSFT  Low MSFT  Close MSFT  Volume MSFT  \
time                                                                  
2000-01-03        NaN        NaN       NaN         NaN          NaN   
2000-01-04        NaN        NaN       NaN         NaN          NaN   
2000-01-05        NaN        NaN       NaN         NaN          NaN   
2000-01-06        NaN        NaN       NaN         NaN          NaN   
2000-01-07        NaN        NaN       NaN         NaN          NaN   
...               ...        ...       ...         ...          ...   
2020-03-15        NaN        NaN       NaN         NaN          NaN   
2020-03-16      140.0   149.3500    135.00      135.42   87905868.0   
2020-03-17      140.0   147.4998    135.00      146.57   81059817.0   
2020-03-18      138.0   146.0000    135.02      140.40   80794307.0   
2020-03-19        NaN        NaN       NaN         NaN          NaN   

            Open GOOG  High GOOG  Low GOOG  Close GOOG  Volume GOOG  ...  \
time                                                                 ...   
2000-01-03        NaN        NaN       NaN         NaN          NaN  ...   
2000-01-04        NaN        NaN       NaN         NaN          NaN  ...   
2000-01-05        NaN        NaN       NaN         NaN          NaN  ...   
2000-01-06        NaN        NaN       NaN         NaN          NaN  ...   
2000-01-07        NaN        NaN       NaN         NaN          NaN  ...   
...               ...        ...       ...         ...          ...  ...   
2020-03-15        NaN        NaN       NaN         NaN          NaN  ...   
2020-03-16    1096.00    1152.27   1074.44     1084.33    4252365.0  ...   
2020-03-17    1093.11    1130.86   1056.01     1119.80    3861489.0  ...   
2020-03-18    1056.51    1106.50   1037.28     1096.80    4220935.0  ...   
2020-03-19        NaN        NaN       NaN         NaN          NaN  ...   

            Open EUROSTOCK50  High EUROSTOCK50  Low EUROSTOCK50  \
time                                                              
2000-01-03         4849.2202         4849.2202        4849.2202   
2000-01-04         4657.8301         4657.8301        4657.8301   
2000-01-05         4541.7500         4541.7500        4541.7500   
2000-01-06         4500.6899         4500.6899        4500.6899   
2000-01-07         4648.2700         4648.2700        4648.2700   
...                      ...               ...              ...   
2020-03-15               NaN               NaN              NaN   
2020-03-16         2557.7100         2557.7100        2302.8401   
2020-03-17         2475.1799         2555.4099        2376.2300   
2020-03-18         2507.3301         2507.3301        2365.7000   
2020-03-19               NaN               NaN              NaN   

            Close EUROSTOCK50  Volume EUROSTOCK50  Open INTEL  High INTEL  \
time                                                                        
2000-01-03          4849.2202                 0.0         NaN         NaN   
2000-01-04          4657.8301                 0.0         NaN         NaN   
2000-01-05          4541.7500                 0.0         NaN         NaN   
2000-01-06          4500.6899                 0.0         NaN         NaN   
2000-01-07          4648.2700                 0.0         NaN         NaN   
...                       ...                 ...         ...         ...   
2020-03-15                NaN                 NaN         NaN         NaN   
2020-03-16          2450.3701         137137000.0       30.11      32.845   
2020-03-17          2530.5000         106905300.0       29.06      33.800   
2020-03-18          2385.8201          98214900.0       30.24      32.455   
2020-03-19                NaN                 NaN         NaN         NaN   

            Low INTEL  Close INTEL  Volume INTEL  
time                                              
2000-01-03        NaN          NaN           NaN  
2000-01-04        NaN          NaN           NaN  
2000-01-05        NaN

In [133]:
# Seleccionar una columna
assets = assets[["Close DJI30","Close CAC40","Close SP500"]]
assets

Close DJI30  Close CAC40  Close SP500
time                                             
2000-01-03   11357.5098    5917.3701    1455.2200
2000-01-04   10997.9297    5672.0200    1399.4200
2000-01-05   11122.6504    5479.7002    1402.1100
2000-01-06   11253.2598    5450.1099    1403.4500
2000-01-07   11522.5596    5539.6099    1441.4700
...                 ...          ...          ...
2020-03-15          NaN          NaN          NaN
2020-03-16   20188.5195    3881.4600    2426.6181
2020-03-17   21237.3809    3991.7800    2436.5000
2020-03-18   19898.9199    3754.8401    2398.1001
2020-03-19          NaN          NaN          NaN

[5732 rows x 3 columns]

In [134]:
# Eliminar los valores faltantes o  NAN
assets = assets.dropna()
assets

Close DJI30  Close CAC40  Close SP500
time                                             
2000-01-03   11357.5098    5917.3701    1455.2200
2000-01-04   10997.9297    5672.0200    1399.4200
2000-01-05   11122.6504    5479.7002    1402.1100
2000-01-06   11253.2598    5450.1099    1403.4500
2000-01-07   11522.5596    5539.6099    1441.4700
...                 ...          ...          ...
2020-03-12   21200.6191    4044.2600    2420.8827
2020-03-13   23185.6191    4118.3599    2418.0191
2020-03-16   20188.5195    3881.4600    2426.6181
2020-03-17   21237.3809    3991.7800    2436.5000
2020-03-18   19898.9199    3754.8401    2398.1001

[5047 rows x 3 columns]

In [137]:
# Reiniciar los indices
assets.reset_index(drop=True)

time  Close DJI30  Close CAC40  Close SP500
0    2000-01-03   11357.5098    5917.3701    1455.2200
1    2000-01-04   10997.9297    5672.0200    1399.4200
2    2000-01-05   11122.6504    5479.7002    1402.1100
3    2000-01-06   11253.2598    5450.1099    1403.4500
4    2000-01-07   11522.5596    5539.6099    1441.4700
...         ...          ...          ...          ...
5042 2020-03-12   21200.6191    4044.2600    2420.8827
5043 2020-03-13   23185.6191    4118.3599    2418.0191
5044 2020-03-16   20188.5195    3881.4600    2426.6181
5045 2020-03-17   21237.3809    3991.7800    2436.5000
5046 2020-03-18   19898.9199    3754.8401    2398.1001

[5047 rows x 4 columns]

In [138]:
# Rolling Media moviles - sacar la media de los 15 primeros, en los siguientes
assets["SMA 15"] = assets[["Close SP500"]].rolling(15).mean()
assets


/tmp/ipykernel_741/3219515475.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  assets["SMA 15"] = assets[["Close SP500"]].rolling(15).mean()


Close DJI30  Close CAC40  Close SP500       SMA 15
time                                                          
2000-01-03   11357.5098    5917.3701    1455.2200          NaN
2000-01-04   10997.9297    5672.0200    1399.4200          NaN
2000-01-05   11122.6504    5479.7002    1402.1100          NaN
2000-01-06   11253.2598    5450.1099    1403.4500          NaN
2000-01-07   11522.5596    5539.6099    1441.4700          NaN
...                 ...          ...          ...          ...
2020-03-12   21200.6191    4044.2600    2420.8827  2445.100287
2020-03-13   23185.6191    4118.3599    2418.0191  2444.029520
2020-03-16   20188.5195    3881.4600    2426.6181  2443.003900
2020-03-17   21237.3809    3991.7800    2436.5000  2442.964567
2020-03-18   19898.9199    3754.8401    2398.1001  2440.551540

[5047 rows x 4 columns]

In [139]:
# Shift - Calcular porcentaje de variacion
assets["Close SP500"].shift(1)

time
2000-01-03          NaN
2000-01-04    1455.2200
2000-01-05    1399.4200
2000-01-06    1402.1100
2000-01-07    1403.4500
                ...    
2020-03-12    2423.1280
2020-03-13    2420.8827
2020-03-16    2418.0191
2020-03-17    2426.6181
2020-03-18    2436.5000
Name: Close SP500, Length: 5047, dtype: float64

In [142]:
# Agrupar por media
arr = [
    [1, 11],
    [1, 10],
    [3, 15],
    [3, 15],
    [3, 10],
]

# Dataframe con el array creado y con  las columnas num y values
df = pd.DataFrame(arr,columns=["num","value"])

 
df

num  value
0    1     11
1    1     10
2    3     15
3    3     15
4    3     10

In [143]:
# Agrupar por media por la columna "num" y la media que de la columna value
df.groupby(by="num").mean()

value
num           
1    10.500000
3    13.333333

In [144]:
# Agrupar por suma
df.groupby(by="num").sum()

value
num       
1       21
3       40

### Matplotlib